"""add outreach_channels table for per-channel outreach tracking

Revision ID: 0b37c89cd6e1
Revises: e4e654b493d5
Create Date: 2026-07-11 18:48:02.366294
"""
import uuid
from datetime import datetime
from alembic import op
import sqlalchemy as sa


revision = '0b37c89cd6e1'
down_revision = 'e4e654b493d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_step', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'channel')
    )
    op.create_index('idx_outreach_person', 'outreach_channels', ['person_id'], unique=False)
    # ### end Alembic commands ###

    # Data backfill: the old single-channel outreach fields on persons (outreach_connection_sent/
    # accepted/messaged/response_notes) predate this table. Since "connection request" is a
    # LinkedIn-specific concept, any person with data logged under the old system gets a
    # 'linkedin' row here so nothing already tracked in production gets silently lost.
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT id, outreach_connection_sent, outreach_connection_accepted, outreach_messaged, "
        "outreach_connection_sent_date, outreach_response_notes, next_step, outreach_updated_by, "
        "outreach_updated_at FROM persons WHERE outreach_connection_sent = :t OR outreach_messaged = :t "
        "OR outreach_response_notes IS NOT NULL"
    ), {"t": True}).fetchall()

    for r in rows:
        (person_id, conn_sent, conn_accepted, messaged, sent_date,
         response_notes, next_step, updated_by, updated_at) = r
        stage_parts = []
        if conn_sent:
            stage_parts.append("Connection request sent")
        if conn_accepted:
            stage_parts.append("accepted")
        if messaged:
            stage_parts.append("messaged")
        stage = " · ".join(stage_parts) if stage_parts else None
        conn.execute(sa.text(
            "INSERT INTO outreach_channels (id, person_id, channel, stage, notes, next_step, "
            "updated_by, updated_at) VALUES (:id, :pid, 'linkedin', :stage, :notes, :next_step, "
            ":updated_by, :updated_at)"
        ), {
            "id": str(uuid.uuid4()), "pid": person_id, "stage": stage, "notes": response_notes,
            "next_step": next_step, "updated_by": updated_by,
            "updated_at": updated_at or datetime.utcnow(),
        })


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_outreach_person', table_name='outreach_channels')
    op.drop_table('outreach_channels')
    # ### end Alembic commands ###
