"""add document_uploads table for dashboard file uploads

Revision ID: 2d87f95e929c
Revises: 44650673ac83
Create Date: 2026-07-11 19:51:29.772681
"""
from alembic import op
import sqlalchemy as sa


revision = '2d87f95e929c'
down_revision = '44650673ac83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('org_name_hint', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uploads_org', 'document_uploads', ['org_id'], unique=False)
    op.create_index('idx_uploads_status', 'document_uploads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_uploads_status', table_name='document_uploads')
    op.drop_index('idx_uploads_org', table_name='document_uploads')
    op.drop_table('document_uploads')
    # ### end Alembic commands ###
