"""add outreach tracking fields to persons

Revision ID: 3c01ecc9779b
Revises: e277ae5a4c31
Create Date: 2026-07-11 12:59:53.241012
"""
from alembic import op
import sqlalchemy as sa


revision = '3c01ecc9779b'
down_revision = 'e277ae5a4c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('outreach_connection_sent', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('outreach_connection_sent_date', sa.DateTime(), nullable=True))
    op.add_column('persons', sa.Column('outreach_connection_accepted', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('outreach_messaged', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('outreach_response_notes', sa.Text(), nullable=True))
    op.add_column('persons', sa.Column('outreach_updated_by', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('outreach_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'outreach_updated_at')
    op.drop_column('persons', 'outreach_updated_by')
    op.drop_column('persons', 'outreach_response_notes')
    op.drop_column('persons', 'outreach_messaged')
    op.drop_column('persons', 'outreach_connection_accepted')
    op.drop_column('persons', 'outreach_connection_sent_date')
    op.drop_column('persons', 'outreach_connection_sent')
    # ### end Alembic commands ###
