"""initial DRIP schema

Revision ID: 3fa05e3abf7f
Revises: 
Create Date: 2026-07-09 15:24:19.378982
"""
from alembic import op
import sqlalchemy as sa


revision = '3fa05e3abf7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('parent_org_id', sa.String(length=36), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('headquarters', sa.String(), nullable=True),
    sa.Column('core_banking', sa.String(), nullable=True),
    sa.Column('crm', sa.String(), nullable=True),
    sa.Column('los', sa.String(), nullable=True),
    sa.Column('lms', sa.String(), nullable=True),
    sa.Column('collections', sa.String(), nullable=True),
    sa.Column('treasury', sa.String(), nullable=True),
    sa.Column('payments', sa.String(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.Column('fraud', sa.String(), nullable=True),
    sa.Column('aml', sa.String(), nullable=True),
    sa.Column('kyc', sa.String(), nullable=True),
    sa.Column('cloud', sa.String(), nullable=True),
    sa.Column('api_gateway', sa.String(), nullable=True),
    sa.Column('ai_initiatives', sa.JSON(), nullable=True),
    sa.Column('annual_revenue_usd', sa.Float(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('assets_usd_billions', sa.Float(), nullable=True),
    sa.Column('founded', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_index(op.f('ix_organizations_short_name'), 'organizations', ['short_name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_segments', sa.JSON(), nullable=True),
    sa.Column('key_benefits', sa.Text(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unsubscribes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account_intelligence',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('sub_segment', sa.String(), nullable=True),
    sa.Column('digital_maturity', sa.Integer(), nullable=True),
    sa.Column('open_banking', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('lifecycle_status', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('readiness', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('last_touch_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('account_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('score_date', sa.DateTime(), nullable=True),
    sa.Column('signal_score', sa.Integer(), nullable=True),
    sa.Column('regulatory_score', sa.Integer(), nullable=True),
    sa.Column('reachability_score', sa.Integer(), nullable=True),
    sa.Column('relationship_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scores_org', 'account_scores', ['org_id'], unique=False)
    op.create_table('org_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_org_id', sa.String(length=36), nullable=False),
    sa.Column('to_org_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_type_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('type_tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'type_tag')
    )
    op.create_index('idx_orgtag_org', 'org_type_tags', ['org_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('full_name_ar', sa.String(), nullable=True),
    sa.Column('current_org_id', sa.String(length=36), nullable=True),
    sa.Column('current_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('business_unit', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('seniority_level', sa.String(), nullable=True),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('decision_weight', sa.Integer(), nullable=True),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=True),
    sa.Column('is_influencer', sa.Boolean(), nullable=True),
    sa.Column('is_connector', sa.Boolean(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('secondary_email', sa.String(), nullable=True),
    sa.Column('email_confidence', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('linkedin_public_id', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('is_ksa_national', sa.Boolean(), nullable=True),
    sa.Column('past_companies', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('reporting_manager_id', sa.String(length=36), nullable=True),
    sa.Column('warmness', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('interaction_lineage', sa.JSON(), nullable=True),
    sa.Column('background_notes', sa.Text(), nullable=True),
    sa.Column('pitch_notes', sa.Text(), nullable=True),
    sa.Column('connection_paths', sa.Text(), nullable=True),
    sa.Column('consent_status', sa.String(), nullable=True),
    sa.Column('consent_date', sa.DateTime(), nullable=True),
    sa.Column('consent_source', sa.String(), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_current_org_id'), 'persons', ['current_org_id'], unique=False)
    op.create_table('product_fit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_reason', sa.Text(), nullable=True),
    sa.Column('pitch_angle', sa.Text(), nullable=True),
    sa.Column('objection_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'product_id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('product_match', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_actioned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_signals_org', 'signals', ['org_id'], unique=False)
    op.create_index('idx_signals_type', 'signals', ['signal_type'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('persona_target', sa.String(), nullable=True),
    sa.Column('sequence_step', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_intelligence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('clients', sa.JSON(), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('implementation_partners', sa.JSON(), nullable=True),
    sa.Column('case_studies', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('buying_committee_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('committee_role', sa.String(), nullable=True),
    sa.Column('engagement', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'person_id', 'product_id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('champion_id', sa.String(length=36), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_person_id', sa.String(length=36), nullable=True),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('from_type', sa.String(), nullable=True),
    sa.Column('to_person_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_org', 'activity_log', ['org_id'], unique=False)
    op.create_index('idx_activity_person', 'activity_log', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_person', table_name='activity_log')
    op.drop_index('idx_activity_org', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('person_relationships')
    op.drop_table('opportunities')
    op.drop_table('drafts')
    op.drop_table('buying_committee_members')
    op.drop_table('vendor_intelligence')
    op.drop_table('templates')
    op.drop_index('idx_signals_type', table_name='signals')
    op.drop_index('idx_signals_org', table_name='signals')
    op.drop_table('signals')
    op.drop_table('product_fit')
    op.drop_index(op.f('ix_persons_current_org_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index('idx_orgtag_org', table_name='org_type_tags')
    op.drop_table('org_type_tags')
    op.drop_table('org_relationships')
    op.drop_index('idx_scores_org', table_name='account_scores')
    op.drop_table('account_scores')
    op.drop_table('account_intelligence')
    op.drop_table('unsubscribes')
    op.drop_table('products')
    op.drop_index(op.f('ix_organizations_short_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
