"""add live bible scoring fields to account_intelligence

Revision ID: 44650673ac83
Revises: 0b37c89cd6e1
Create Date: 2026-07-11 19:04:41.364451
"""
from alembic import op
import sqlalchemy as sa


revision = '44650673ac83'
down_revision = '0b37c89cd6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_intelligence', sa.Column('effective_opportunity', sa.Float(), nullable=True))
    op.add_column('account_intelligence', sa.Column('decision_score', sa.Float(), nullable=True))
    op.add_column('account_intelligence', sa.Column('scoring_inputs', sa.JSON(), nullable=True))
    op.add_column('account_intelligence', sa.Column('scored_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_intelligence', 'scored_at')
    op.drop_column('account_intelligence', 'scoring_inputs')
    op.drop_column('account_intelligence', 'decision_score')
    op.drop_column('account_intelligence', 'effective_opportunity')
    # ### end Alembic commands ###
