"""add tier, indian-origin, outreach fields to person

Revision ID: e277ae5a4c31
Revises: 3fa05e3abf7f
Create Date: 2026-07-11 12:31:29.641763
"""
from alembic import op
import sqlalchemy as sa


revision = 'e277ae5a4c31'
down_revision = '3fa05e3abf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('priority_tier', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('is_indian_origin', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('last_activity_summary', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('next_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'next_step')
    op.drop_column('persons', 'last_activity_summary')
    op.drop_column('persons', 'is_indian_origin')
    op.drop_column('persons', 'priority_tier')
    # ### end Alembic commands ###
