"""add bd ecosystem flow column and priority to persons

Revision ID: e4e654b493d5
Revises: 3c01ecc9779b
Create Date: 2026-07-11 18:21:18.266167
"""
from alembic import op
import sqlalchemy as sa


revision = 'e4e654b493d5'
down_revision = '3c01ecc9779b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('bd_flow_column', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('bd_priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'bd_priority')
    op.drop_column('persons', 'bd_flow_column')
    # ### end Alembic commands ###
